import { Inter } from "next/font/google";
import Link from "next/link";
import Head from "next/head";
import Blog_card from "@/components/blog_card";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiet Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <div className="flex flex-col mx-auto mt-28">
          <p className="mx-auto font-bold text-5xl">CodeBlox</p>
          <p className="font-mono my-8 ">
            A blogging website, by a coder for the coders
          </p>
        </div>
      </div>

      <div className="flex flex-col items-center">
        <span className="text-3xl font-sans self-start ml-8 font-medium">
          Latest Blogs
        </span>
        {/* <div className="w-full border border-blue-600 "></div> */}
        <div className="cards grid lg:grid-cols-3 sm:grid-cols-2 mt-5 pb-6 gap-y-7 ">
          <Blog_card title="Caras" />
          <Blog_card title="Caras" />
          <Blog_card title="Caras" />
        </div>
        <Link href="/about">
        <button class="rounded-md border border-gray-600 px-3.5 py-1.5 mb-5 text-base font-semibold leading-7 text-gray-600 hover:bg-gray-300/40 hover:shadow-violet-200 hover:shadow-lg transition-all ">
          See More
        </button>
        </Link>
      </div>
    </>
  );
}
